CREATE SCHEMA IF NOT EXISTS gold_predict;

SET search_path TO gold_predict;

CREATE TABLE IF NOT EXISTS gold_data (
    id SERIAL PRIMARY KEY,
    datetime TIMESTAMP DEFAULT NULL,
    price DOUBLE PRECISION DEFAULT NULL,
    change DOUBLE PRECISION DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS oil_data (
    id SERIAL PRIMARY KEY,
    datetime TIMESTAMP DEFAULT NULL,
    price DOUBLE PRECISION DEFAULT NULL,
    change DOUBLE PRECISION DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS dxy_data (
    id SERIAL PRIMARY KEY,
    datetime TIMESTAMP DEFAULT NULL,
    price DOUBLE PRECISION DEFAULT NULL,
    change DOUBLE PRECISION DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS spx_data (
    id SERIAL PRIMARY KEY,
    date TIMESTAMP DEFAULT NULL,
    open DOUBLE PRECISION DEFAULT NULL,
    high DOUBLE PRECISION DEFAULT NULL,
    low DOUBLE PRECISION DEFAULT NULL,
    close DOUBLE PRECISION DEFAULT NULL,
    volume DOUBLE PRECISION DEFAULT NULL,
    percent DOUBLE PRECISION DEFAULT NULL
);
