CREATE SCHEMA IF NOT EXISTS gold_predict;

SET search_path TO gold_predict;

CREATE TABLE IF NOT EXISTS dxy_data (    
    Date TIMESTAMP DEFAULT NULL,
    dxy_last DOUBLE PRECISION DEFAULT NULL,
    dxy_open DOUBLE PRECISION DEFAULT NULL,
    dxy_high DOUBLE PRECISION DEFAULT NULL,
    dxy_low DOUBLE PRECISION DEFAULT NULL,
    dxy_change_percent DOUBLE PRECISION DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS sp500_data (    
    Date TIMESTAMP DEFAULT NULL,
    sp500_last DOUBLE PRECISION DEFAULT NULL,
    sp500_open DOUBLE PRECISION DEFAULT NULL,
    sp500_high DOUBLE PRECISION DEFAULT NULL,
    sp500_low DOUBLE PRECISION DEFAULT NULL,
    sp500_change_percent DOUBLE PRECISION DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS gold_data (    
    Date TIMESTAMP DEFAULT NULL,
    gold_last DOUBLE PRECISION DEFAULT NULL,
    gold_open DOUBLE PRECISION DEFAULT NULL,
    gold_high DOUBLE PRECISION DEFAULT NULL,
    gold_low DOUBLE PRECISION DEFAULT NULL,
    gold_volume DOUBLE PRECISION DEFAULT NULL,
    gold_change_percent DOUBLE PRECISION DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS oil_data (    
    Date TIMESTAMP DEFAULT NULL,
    oil_last DOUBLE PRECISION DEFAULT NULL,
    oil_open DOUBLE PRECISION DEFAULT NULL,
    oil_high DOUBLE PRECISION DEFAULT NULL,
    oil_low DOUBLE PRECISION DEFAULT NULL,
    oil_volume DOUBLE PRECISION DEFAULT NULL,
    oil_change_percent DOUBLE PRECISION DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS history_data (    
    Date TIMESTAMP DEFAULT NULL,
    open DOUBLE PRECISION DEFAULT NULL,
    high DOUBLE PRECISION DEFAULT NULL,
    low DOUBLE PRECISION DEFAULT NULL,
    close DOUBLE PRECISION DEFAULT NULL,
    volume INTEGER DEFAULT NULL
);
